import Head from 'next/head';
import { useAppBridge } from '@/hooks';

export default function Home() {
	const { completed } = useAppBridge({ type: 'space-plugin', oauth: true });

	return (
		<>
			<Head>
				<title>Storyblok Next Tool Starter</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main style={{ width: '100%', height: '100%', margin: 0, padding: 0 }}>
				{completed ? (
					<iframe
						src={process.env.APPURL}
						style={{ width: '100%', height: '100%', border: 'none' }}
						allowFullScreen
					/>
				) : (
					<p>Loading authentication...</p>
				)}
			</main>
		</>
	);
}
